myblog/blog/home/models.py
from flask_sqlalchemy  import SQLAlchemy
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from flask_admin.contrib.sqla import ModelView
from flask import redirect, url_for
from flask_admin.form import SecureForm
from flask_admin.contrib.sqla import ModelView
from datetime import datetime
from flask import abort
#import flask_whooshalchemy as wa
import random
#import flask.ext.whooshalchemy as whooshalchemy

db = SQLAlchemy()

prettyfy="<pre class='prettyprint'></pre>"
class Blogpost(db.Model,UserMixin):
    __searchable__ = ['title', 'content']
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    subtitle = db.Column(db.String(500))
    author = db.Column(db.String(20))
    date_posted = db.Column(db.DateTime)
    image_url = db.Column(db.String(20000000000000))
    content = db.Column(db.Text, default=prettyfy)
    total_read = db.Column(db.Integer, default=0)

class Settings(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    blogname = db.Column(db.String(50))
    slogan = db.Column(db.String(500))
    myurl = db.Column(db.String(2000))
    about_me = db.Column(db.Text)
    about_blog = db.Column(db.Text)

class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    fullname=db.Column(db.String(500))
    username = db.Column(db.String(222),unique=True)
    email=db.Column(db.String(300),unique=True)
    password=db.Column(db.String(500))
    role=db.Column(db.String(10),default=0)

class Comment_System(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    api_name = db.Column(db.String(50))
    purpose = db.Column(db.String(500))
    code = db.Column(db.Text)

class Coin(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    api_name = db.Column(db.String(50))
    purpose = db.Column(db.String(500))
    code = db.Column(db.Text)





class LoadViews(ModelView):
    def is_accessible(self):
        try:

            if current_user.role ==1:
                return current_user.is_authenticated
            else:
                return self.inaccessible_callback(abort(404)) #redirect(url_for('member.dashbaoord'))
        except AttributeError:
            return self.inaccessible_callback(abort(404))




    def inaccessible_callback(self, name, **kwargs):
        if current_user.AnonymousUserMixin:
            return redirect(url_for('homepage.index'))
        # redirect to login page if user doesn't have access
    #column_searchable_list = ['first_name','last_name','username']




class ControlBlogPost(ModelView):
    def BlogpostControl(self):
        try:

            if current_user.role ==1:
                return current_user.is_authenticated
            else:
                return self.inaccessible_callback(abort(404))
        except AttributeError:
            return self.inaccessible_callback(abort(404))



    create_modal = True
    edit_modal = True
    can_create = True
    can_edit = True
    can_delete = True
    can_export = True
    can_view_details = True
    column_exclude_list = ['content']
    form_base_class = SecureForm
    column_searchable_list = ['title','content']

myblog/blog/__init__.py
from flask import Flask
from flask_mail import Mail, Message

from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand


from blog.home.views import hom
from blog.home.models import *
from blog.auth.views import login
#import flask.ext.whooshalchemy as whooshalchemy




from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from sqlalchemy.exc import *
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
#import flask_whooshalchemy as wa


app=Flask(__name__)
app.config.from_pyfile('config.py')
app.config['WHOOSH_BASE'] = 'tmp/whoosh/base'
mail =Mail(app)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'signin'
#login_manager = LoginManager()
migrate = Migrate(app,db)
manager = Manager(app)

manager.add_command('db',MigrateCommand)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


#admin = Admin(app, name='Control Panel')
#admin.add_view(Blogpost, db.session)
admin = Admin(app,name='Control Panel')
admin.add_view(ControlBlogPost(Blogpost,db.session))
admin.add_view(LoadViews(Settings,db.session))
admin.add_view(LoadViews(Comment_System,db.session))
admin.add_view(LoadViews(User,db.session))
#whooshalchemy.whoosh_index(app, Blogpost)



db.init_app(app)

app.register_blueprint(home.views.hom)
app.register_blueprint(auth.views.login)

myblog/blog/home/views.py
from flask import Blueprint , render_template,request,flash,jsonify
from models import *
#import flask.ext.whooshalchemy as whooshalchemy
import random
import uuid
code = uuid.uuid4().hex
print(code)

hom=Blueprint('homepage',__name__)



@hom.route('/')
@hom.route('/home')
def index():
	config=Settings.query.first()
	page = request.args.get('page',1,type=int)
	#post = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()
	#post = Blogpost.query.paginate(per_page=5,page=page,error_out=True)
	post = Blogpost.query.order_by(Blogpost.date_posted.desc()).paginate(per_page=5,page=page,error_out=True)
	#threads = Blogpost.query.paginate(per_page=5,page=1,error_out=True)
	#threads=Blogpost.query.order_by(Blogpost.date_posted.desc()).paginate(per_page=5,page=1,error_out=True)
	return render_template('home/index.html',config=config,post=post)

@hom.route('/article/<int:post_id>')
def article(post_id):
	config=Settings.query.first()
	poster = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()
	#threads = Blogpost.query.paginate(per_page=5,page=post_id,error_out=True)
	config=Settings.query.first()
	post = Blogpost.query.filter_by(id=post_id).one()
	comment_api=Comment_System.query.first()
	#threads=Blogpost.query.order_by(Blogpost.date_posted.desc()).paginate(per_page=5,page=post_id,error_out=True)
	return render_template('home/single.html',
		post=post,config=config,
		comment_api=comment_api,poster=poster)
"""

@hom.route('/search')
def search():
	threads=Blogpost.query.whoosh_search(request.args.get('query'))
	config=Settings.query.first()
	post = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()
	return render_template('home/test.html',threads=threads,
		post=post,config=config)
"""






@hom.route('/post/<int:post_id>')
def post(post_id):
	config=Settings.query.first()
	post = Blogpost.query.filter_by(id=post_id).one()
	comment_api=Comment_System.query.first()

	return render_template('home/single.html',post=post,
		config=config,
		comment_api=comment_api)

@hom.route('/golive')
def golive():
	config=Settings.query.first()
	return redirect(url_for('homepage.live',code=code,config=config))
@hom.route('/live/<code>')
def live(code):
	config=Settings.query.first()
	comment_api=Comment_System.query.first()
	return render_template('./home/live.html',
		config=config,
		comment_api=comment_api)





@hom.route('/createdb')
def createdb():
	db.create_all()
	return("done")

@hom.route('/emptydb')
def emptydb():
	db.drop_all()
	return("Deleted")

myblog/blog/templates/home/footer.html
<SCRIPT data-cfasync="false" SRC="//bdv.bidvertiser.com/BidVertiser.dbm?pid=803768&bid=1959356" TYPE="text/javascript"></SCRIPT>
<!-- End BidVertiser code -->





<footer>


      <div class="row">

      	<div class="twelve columns">
				<ul class="social-links">
               <li><a href="https://www.facebook.com/codesideacademy/"><i class="fa fa-facebook"></i></a></li>
               <li><a href="https://twitter.com/Olaide_DS"><i class="fa fa-twitter"></i></a></li>
               <li><a href="https://plus.google.com/113782000185269688487"><i class="fa fa-google-plus"></i></a></li>
               <li><a href="https://github.com/Abdulkereem/"><i class="fa fa-github-square"></i></a></li>
               <li><a href="https://www.instagram.com/ironside222/"><i class="fa fa-instagram"></i></a></li>
               <li><a href="#"><i class="fa fa-flickr"></i></a></li>
               <li><a href="#"><i class="fa fa-skype"></i></a></li>
            </ul>
      	</div>

         <div class="six columns info">

            <h3>About CodeSide Academy</h3>

            <p>
            {{config.about_blog}}
            </p>

         </div>

         <div class="four columns">



         </div>

         <div class="two columns">
            <h3 class="social">Navigate</h3>

            <ul class="navigate group">
               <li><a href="/">Home</a></li>
               <li><a href="#">About</a></li>
            </ul>
         </div>

         <p class="copyright">&copy; Copyright 2018 CodeSide Academy.</p>

      </div> <!-- End row -->

      <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-chevron-up"></i></a></div>

   </footer> <!-- End Footer-->


   <!-- Java Script
   ================================================== -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script src="{{ url_for('static', filename='home/js/jquery-1.10.2.min.js') }}"s></script>
   <script type="text/javascript" src="{{ url_for('static', filename='home/js/jquery-migrate-1.2.1.min.js') }}"></script>
   <script src="{{ url_for('static', filename='home/js/main.js') }}"></script>
   <!-- Begin BidVertiser code -->

myblog/blog/templates/home/header.html
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>{{config.blogname}}.</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="{{ url_for('static', filename='home/css/default.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='home/css/layout.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='home/css/media-queries.css') }}">
	<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

   <!-- Script
   ================================================== -->
	<script src="{{ url_for('static', filename='home/js/modernizr.js') }}"></script>
	<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?lang=css&amp;skin=sunburst"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<meta name="google-site-verification" content="Dn3ajYqqUa6fRZHImT_0D5hG4p_stJjkw2j75Qu96VA" />

   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='home/images/CodeSide Logo fb.jpg') }}" >

    <meta name="google-site-verification" content="ny4FxJ4ww9OdbDu23WiLrUwW05y5StPdE7ONvBIf2xA" />


</head>

<body>

   <!-- Header
   ================================================== -->
   <header id="top">

   	<div class="row">

   		<div class="header-content twelve columns">

		      <h1 id="logo-text"><a href="#" title="">{{config.blogname}}</a></h1>
				<p id="intro">{{config.slogan}}</p>

			</div>

	   </div>

	   <nav id="nav-wrap">
	   	{% if current_user.is_authenticated %}
	   	   	<a class="mobile-btn" href="{{ url_for('homepage.golive') }}" title="Show navigation">LiVE streaming class</a>
	   		   <a class="mobile-btn" href="#" title="Hide navigation">Hide Menu</a>

	   	   	<div class="row">

	   			   	<ul id="nav" class="nav">
	   			      	<li class="current"><a href="{{ url_for('homepage.index') }}">Home</a></li>

	   			      	<li class="has-children"><a href="#">{{current_user.username}}</a>
	   	                  <ul>
	   	                  	<li><a href="{{url_for('login.logout')}}" >Logout</a></li>
	   	                  </ul>
	   	               </li>
	   	               <li><a href="{{ url_for('homepage.golive') }}">Live Class</a></li>
	   	               <li><a href="{{config.myurl}}">About me</a></li>

	   			   	</ul>

	   	{% else %}
	   	<a class="mobile-btn" href="{{ url_for('homepage.golive') }}" title="Show navigation">LiVE streaming class</a>
		   <a class="mobile-btn" href="#" title="Hide navigation">Hide Menu</a>

	   	<div class="row">

			   	<ul id="nav" class="nav">
			      	<li class="current"><a href="{{ url_for('homepage.index') }}">Home</a></li>

			      	<li class="has-children"><a href="#">Account</a>
	                  <ul>
	                     <li><a onclick="document.getElementById('modal-wrapper').style.display='block'"href="#" >Create Account</a></li>
	                     <li><a onclick="document.getElementById('login').style.display='block'" href="#">Login</a></li>
	                  </ul>
	               </li>
	               <li><a href="{{ url_for('homepage.golive') }}">Live Class</a></li>
	               <li><a href="">About me</a></li>

			   	</ul> <!-- end #nav -->

	   	</div>
	   	{% endif %}
	   </nav> <!-- end #nav-wrap -->

   </header> <!-- Header End -->
   {% include './home/pop_up/index.html' %}
   {% include './home/pop_up/login.html' %}
   <div>

   	{% with messages = get_flashed_messages() %}
  {% if messages %}
    <script>
      var messages = {{ messages | safe }};
      for (var i=0; i<messages.length; i++) {
        alert(messages[i]);
      }
    </script>
  {% endif %}
{% endwith %}
   </div>

myblog/blog/templates/home/index.html
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
{% include 'home/header.html' %}

   <!-- Content
   ================================================== -->

   <div id="content-wrap">
     <!-- Begin BidVertiser code -->
<SCRIPT data-cfasync="false" SRC="//bdv.bidvertiser.com/BidVertiser.dbm?pid=803768&bid=1959356" TYPE="text/javascript"></SCRIPT>
<!-- End BidVertiser code -->
   	<div class="row">

   		<div id="main" class="eight columns">

	   		<article class="entry">
	   				{% for posts in post.items %}
					<header class="entry-header">

						<h2 class="entry-title">
							<a href="{{ url_for('homepage.article', post_id=posts.id) }}" title="">{{posts.title |safe}}</a>
						</h2>

						<div class="entry-meta">
							<ul>
								<li>{{ posts.date_posted.strftime('%B %d, %Y') }}</li>
								<span class="meta-sep">&bull;</span>

								<span class="meta-sep">&bull;</span>
								<li>{{posts.author}}</li>
							</ul>
						</div>

					</header>

					<div id="content" class="entry-content">
						<p>{{posts.subtitle |safe}}</p>
                  <img src="{{posts.image_url}}">
					</div>
					<br><br>
					{% endfor %}

				</article> <!-- end entry -->

            <div>



            </div>

						,

   		</div> <!-- end main -->

   		<div id="sidebar" class="four columns">

   			<div class="widget widget_search">
                  <h3>Search</h3>
                  <script>
  (function() {
    var cx = '008103393209601258544:e0nsoa3dhgi';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>               </div>

   			<div class="widget widget_categories group">
   				<h3>Tutorials</h3>
               {% for posts in post.items %}
   				<ul>
						<li><a href="{{ url_for('homepage.article', post_id=posts.id) }}" title="">{{posts.title |safe}}</a></li>
					</ul>
               {% endfor %}
				</div>



				<div class="widget widget_text group">
					<h3>About me</h3>
               <img src="{{ url_for('static', filename='home/images/1.jpg') }}" style="border-radius: 500px; size: height: 100px; width: 150px;">

   				<p>{{config.about_me}}</p>

   			</div>

   			<div class="widget widget_tags">
               <h3>Post Tags.</h3>
               {% for page in post.items%}
               <div class="tagcloud group">
                	<a href="#">{{page.title |safe}}</a>
               </div>
               {% endfor %}
            </div>


             <!-- Begin BidVertiser code -->
<SCRIPT data-cfasync="false" SRC="//bdv.bidvertiser.com/BidVertiser.dbm?pid=803768&bid=1959356" TYPE="text/javascript"></SCRIPT>
<!-- End BidVertiser code -->


<iframe src="https://get.cryptobrowser.site/promo/ad/1/2046331/" style="width: 120px; height: 600px" frameborder="no"></iframe>
   		</div> <!-- end sidebar -->

   	</div> <!-- end row -->
 <center>
         {% for page_num in post.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
               {% if post.page == page_num %}
                  <a class="button" href="{{url_for('homepage.index',page=page_num)}}">{{page_num}}</a>
               {% else %}
                  <a class="button" href="{{url_for('homepage.index',page=page_num)}}">{{page_num}}</a>
               {% endif %}

            {% else %}
              ...
            {% endif %}
         {% endfor %}
      </center>

   </div> <!-- end content-wrap -->


   <!-- Footer
   ================================================== -->
   {% include 'home/footer.html' %}



</body>

</html>

myblog/blog/templates/home/live.html
<!DOCTYPE html>
<html>
<head>
	<title>Live Class</title>

	{% include './home/header.html' %}
</head>
<body>
	<center>
         
	<div>
           <br><br><br><br><br>
		<iframe style="size: height: 100%; width: 1000px;"  src="https://www.youtube.com/embed/live_stream?channel=UCwZd2y4g5uxQk7jWzghCrdA" frameborder="0" allowfullscreen></iframe>
          <br><br><br><br><br><br>
	
	</div>
     
     <hr>
          {{comment_api.code|safe}}
	
               </center>
	</center>

	{% include './home/footer.html' %}
</body>
</html>

myblog/blog/templates/home/pop_up/alert.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
#dialogoverlay{
	display: none;
	opacity: .8;
	position: fixed;
	top: 0px;
	left: 0px;
	background: #FFF;
	width: 100%;
	z-index: 10;
}
#dialogbox{
	display: none;
	position: fixed;
	background: #000;
	border-radius:7px; 
	width:550px;
	z-index: 10;
}
#dialogbox > div{ background:#FFF; margin:8px; }
#dialogbox > div > #dialogboxhead{ background: #666; font-size:19px; padding:10px; color:#CCC; }
#dialogbox > div > #dialogboxbody{ background:#333; padding:20px; color:#FFF; }
#dialogbox > div > #dialogboxfoot{ background: #666; padding:10px; text-align:right; }
</style>
<script>
function CustomAlert(){
    this.render = function(dialog){
        var winW = window.innerWidth;
        var winH = window.innerHeight;
        var dialogoverlay = document.getElementById('dialogoverlay');
        var dialogbox = document.getElementById('dialogbox');
        dialogoverlay.style.display = "block";
        dialogoverlay.style.height = winH+"px";
        dialogbox.style.left = (winW/2) - (550 * .5)+"px";
        dialogbox.style.top = "100px";
        dialogbox.style.display = "block";
        document.getElementById('dialogboxhead').innerHTML = "Acknowledge This Message";
        document.getElementById('dialogboxbody').innerHTML = dialog;
        document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Alert.ok()">OK</button>';
    }
	this.ok = function(){
		document.getElementById('dialogbox').style.display = "none";
		document.getElementById('dialogoverlay').style.display = "none";
	}
}
var Alert = new CustomAlert();
</script>
</head>
<body>
<div id="dialogoverlay"></div>
<div id="dialogbox">
  <div>
    <div id="dialogboxhead"></div>
    <div id="dialogboxbody"></div>
    <div id="dialogboxfoot"></div>
  </div>
</div>
<h1>My web document content ...</h1>
<h2>My web document content ...</h2>
<button onclick="alert('You look very pretty today.')">Default Alert</button>
<button onclick="Alert.render('You look very pretty today.')">Custom Alert</button>
<button onclick="Alert.render('And you also smell very nice.')">Custom Alert 2</button>
<h3>My web document content ...</h3>
</body>
</html>

myblog/blog/templates/home/single.html
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
{% include 'home/header.html' %}
   <!-- Content
   ================================================== -->
   <div id="content-wrap">

   	<div class="row">

   		<div id="main" class="eight columns">

   			<article class="entry">

					<header class="entry-header">

						<h2 class="entry-title">
							{{post.title |safe}}
						</h2>

						<div class="entry-meta">
							<ul>
								<li>{{post.date_posted.strftime('%B %d, %Y,%X') }}</li>
								<span class="meta-sep">&bull;</span>
								<span class="meta-sep">&bull;</span>
								<li><b>Posted By</b>  {{post.author}}</li>
							</ul>
						</div>

					</header>

					<div class="entry-content-media">
						<div class="post-thumb">
							<img src="{{post.image_url}}">
						</div>
					</div>

					<div class="entry-content">
						<p class="lead">{{post.content |safe}}</p>
					</div>



				</article>







				<!-- Comments
            ================================================== -->
            {{comment_api.code|safe}}


               </center>
   			<div class="widget widget_categories group">
   				<h3>Tutorials.</h3>
   				{% for posts in poster %}
          <ul>
            <li><a href="{{ url_for('homepage.article', post_id=posts.id) }}" title="">{{posts.title |safe}}</a></li>
          </ul>
               {% endfor %}
				</div>

				<div class="widget widget_text group">
				<SCRIPT data-cfasync="false" SRC="//bdv.bidvertiser.com/BidVertiser.dbm?pid=803768&bid=1959356" TYPE="text/javascript"></SCRIPT>

   			</div>

   			<div class="widget widget_tags">
               <h3></h3>

               <div class="tagcloud group">

               <div class="tagcloud group">

               </div>

               </div>

            </div>

<iframe src="https://get.cryptobrowser.site/promo/ad/1/2046331/" style="width: 120px; height: 600px" frameborder="no"></iframe>

   		</div> <!-- end sidebar -->

  		</div> <!-- end row -->

   </div> <!-- end content-wrap -->

   <!-- Footer
   ================================================== -->
   {% include 'home/footer.html' %}

</body>

</html>

myblog/blog/templates/home/test.html
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
{% include 'home/header.html' %}

   <!-- Content
   ================================================== -->
   <div id="content-wrap" class="pagination">

   	<div class="row">

   		<div id="main" class="eight columns">

	   		<article class="entry">
	   				{% for threadss in threads %}
					<header class="entry-header">
						
						<h2 class="entry-title">
							<a href="{{ url_for('homepage.post', post_id=threadss.id) }}" title="">{{threadss.title}}</a>
						</h2> 				 
					
						<div class="entry-meta">
							<ul>
								<li>{{ threadss.date_posted.strftime('%B %d, %Y') }}</li>
								<span class="meta-sep">&bull;</span>								
								
								<span class="meta-sep">&bull;</span>
								<li>{{threadss.author}}</li>
							</ul>
						</div> 
					 
					</header> 
					
					<div id="content" class="entry-content">
						<p>{{threadss.subtitle}}</p>
                  <img src="{{threadss.image_url}}">
					</div> 
					{% endfor %}

				</article> <!-- end entry -->

            <div>
               {% for page in threads %}
                  {% if page %}
                  <a href="{{url_for('homepage.page',post_id=page)}}">{{page}}</a>
                  {% else %}
                     ...
                  {% endif %}
               {% endfor %}
               
               
            </div>
				
						

   		</div> <!-- end main -->

   		<div id="sidebar" class="four columns">

   			<div class="widget widget_search">
                  <h3>Search</h3> 
                  <form action="search" method="GET">

                     <input type="text" value="Search here..." onblur="if(this.value == '') { this.value = 'Search here...'; }" onfocus="if (this.value == 'Search here...') { this.value = ''; }" class="text-search">
                     <input type="submit" value="" class="submit-search">

                  </form>
               </div>

   			<div class="widget widget_categories group">
   				<h3>Tutorials</h3> 
               {% for posts in threads %}
   				<ul>
						<li><a href="#" title="">{{posts.title}}</a> ({{posts.total_read}})</li>						
					</ul>
               {% endfor %}
				</div>




				<div class="widget widget_text group">
					<h3>Widget Text.</h3>

   				<p>Lorem ipsum Ullamco commodo laboris sit dolore commodo aliquip incididunt fugiat esse dolor aute fugiat minim eiusmod do velit labore fugiat officia ad sit culpa labore in consectetur sint cillum sint consectetur voluptate adipisicing Duis irure magna ut sit amet reprehenderit.</p>

   			</div>

   			<div class="widget widget_tags">
               <h3>Post Tags.</h3>
               {% for page in threads %}
               <div class="tagcloud group">
                	<a href="#">{{page.title}}</a>
               </div>
               {% endfor %}
            </div>

            <div class="widget widget_popular">
               <h3>Popular Post.</h3>

               <ul class="link-list">
                  <li><a href="#">Sint cillum consectetur voluptate.</a></li>
                  <li><a href="#">Lorem ipsum Ullamco commodo.</a></li>
                  <li><a href="#">Fugiat minim eiusmod do.</a></li>                     
               </ul>
                  
            </div>
   			
   		</div> <!-- end sidebar -->

   	</div> <!-- end row -->

   </div> <!-- end content-wrap -->
   

   <!-- Footer
   ================================================== -->
   {% include 'home/footer.html' %}

   

</body>

</html>